baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium-theme"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Posts"
    url = "/post"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rtravis89"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/fledglingstat"
    
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]