baseurl = "/"
languageCode = "en-us"
title = "Fledgling Statistician"
theme = "hugo-lithium-theme"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "All Posts"
    url = "/post"
[[menu.main]]
    name = "Tutorials"
    url = "/tutorials"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rtravis89"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/fledglingstat"
[[menu.main]]
   name = "LinkedIn"
   url = "https://www.linkedin.com/in/rtravis89"
    
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    description = "A website built through Hugo and blogdown."

    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "atom-one-dark"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
