---
title: Some Books I Read July
author: ~
date: '2018-07-23'
slug: some-books-i-read-July
categories: []
tags: []
---

###**The Dilemmas of Lenin: Terrorism, War, Empire, Love, Revolution by Tariq Ali**
A very interesting biography of Lenin. The book isn't a traditional biography. Instead, it's a kind of intellectual biography focused around particular topics. Some of the topics, Bolshevik military strategy during the Civil War for instance, don't mention Lenin at all. Additionally there are chapters on terrorism in Tsarist Russia, and the work of feminist Bolsheviks. Ultimately, the book seeks to show that the revolution would not have occurred if it weren't for Lenin. It does a good job of presenting events in context, particularly the absolute brutality of the Tsarist regime from maybe the 1870s onward. I learned a lot from the book (like that the US sent troops into Russia after WWI) and found it very interesting and fun to read. I definitely recommend.

[Nice review of the book by Branko Milanovic.](http://glineq.blogspot.com/2017/05/lenin-in-his-time-review-of-tariq-alis.html)

###**Lewis Carroll in Numberland: His Fantastical Mathematical Logical Life by Robin Wilson**
A biography of Lewis Carroll (Charles Dodgson) that focuses around his mathematical work in a non-technical way. The book is short and fun. The best parts for me were the snippets from Alice in Wonderland (just a fantastic book) and Dodgson's work on elections and tournament mathematics. There are snippets of Dodgson's cleverisms throughout the book, which are also a highlight. Worth reading just to motivate you to go back and read Carroll.


###**The Invention of Nature by Andrea Wulf**
The book starts by asking how Alexander von Humboldt has been all but forgotten in our day and age when he was so famous in his own. Humboldt interacted with, in one capacity or another, almost all the greats of his time (1769-1859). Thomas Jefferson, Napoleon, Simon Bolivar, as well as essentially every famous scientist during his lifetime. Humboldt's scientific study was all of Nature. He wrote about a very wide variety of topics ranging from meteorology, biogeography, to the politics of colonial South America. He went on scientific expeditions to South America and Siberia and climbed some of the world's tallest mountains. The book also has chapters on famous individuals who were influenced by Humboldt, like John Muir (father of national parks in the US) and Henry David Thoreau. Overall the book is a very entertaining account of a very important but neglected scientist.    

###**Raising the Dead: The Men Who Created Frankenstein by Andy Dougan**
A decent book on some of the medical science that influenced the writing of Frankenstein. Some of the more interesting topics in the book revolved around the extreme lengths anatomists went to acquire human cadavers, grave robbing for instance. People even ended up being murdered so that their bodies could be sold to scientists. The most disturbing part of the book to me had nothing to do with electrocuting dead bodies (galvanism), but instead the trial, imprisonment, and eventual executing by hanging of Matthew Clydesdale for murder. Whose body is subsequently used in an experiment by Andrew Ure. The title and to some degree the content of the book strike me as a little sexist since it was a woman who created Frankenstein and the book spends probably as much or more time on Percy Shelley as it does on Mary. 