---
title: Some books I read in August
author: ~
date: '2018-08-19'
slug: some-books-i-read-in-august
categories: []
tags: [books]
---

###**October - China Mieville**
China Mieville is a very good science fiction writer, so I was intrigued when I saw that he wrote a book about the Russian revolution of 1917. Except for the first chapter that quickly covers the history leading up to the revolution and the final epilogue chapter, the book is organized so that each chapter represents a month starting from the overthrow of the Tsar in February to October when Lenin and the Bolsheviks take power. I think the month by month organization might have been a bit of a mistake since the real meat of the story is in February and October. These two chapters, plus the pre-history and epilogue, are the best in the book. The book does a good job of weaving a narrative that captures the chaos of the moment without lapsing into the a kind of historical determinism where the Stalinist terror that was to follow was already pre-determined. The struggle between the Marxist ideology of the day, which said Russia was not ready for a socialist revolution, and the realities of the political situation is particularly well covered. Overall the book is definitely worth reading. 

Ryan Cooper wrote a nice review back in 2017 [here](http://theweek.com/articles/712961/lessons-russian-revolution-100-years-later).

###**Revolutionary Russia (1891 - 1991) - Orlando Figes**
Unlike October, or [The Dilemmas of Lenin](https://ryantravis.netlify.com/post/some-books-i-read-july/) which I reviewed last month, Revolutionary Russia by Orlando Figes covers the entire history, as well as some of the pre-history, of the Soviet Union. It does all this in a mere 300 or so pages. Normally, I consider conciseness a virtue. The issue with this book is the difficulty of reading about a new tragedy every few pages. The period between when the civil war starts, where the bolsheviks justify ever more harsh methods to combat the forces of reaction, to the terror of the Stalin makes for tough reading. 
...to be continued.
###**Neverwhere - Neil Gaiman**